<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<!--i.新闻标题-->
<!--ii.新闻图片-->
<!--iii.新闻简介-->
<!--iv.新闻内容-->
<!--v.排序-->
<!--vi.是否推荐-->
<!--vii.是否显示-->
<center>
    <form action="add" method="post" enctype="multipart/form-data">
    <table>
        <tr>
            <td>新闻标题:</td>
            <td><input type="text" name="title"></td>
        </tr>

        <tr>
            <td>新闻图片:</td>
            <td><input type="file" name="img"></td>
        </tr>

        <tr>
            <td>新闻简介:</td>
            <td><input type="text" name="info"></td>
        </tr>

        <tr>
            <td>新闻内容:</td>
            <td>
                <textarea name="content" id="" cols="30" rows="10">

                </textarea>
            </td>
        </tr>

        <tr>
            <td>排序:</td>
            <td><input type="text" name="sort"></td>
        </tr>

        <tr>
            <td>是否推荐:</td>
            <td>
                <input type="radio" name="istuijian" value="0">推荐
                <input type="radio" name="istuijian" value="1">不推荐
            </td>
        </tr>

        <tr>
            <td>是否显示:</td>
            <td><input type="radio" name="isshow" value="2">不显示
                <input type="radio" name="isshow" value="3">显示
            </td>
        </tr>

        <tr>
            <td></td>
            <td><input type="submit" value="提交"></td>
        </tr>
    </table>
    </form>
</center>

</body>
</html>