<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
     <center>
         <form action="add_type" method="post">
             <table border="1">
                 <tr>
                     <td>分类名称</td>
                     <td>
                         <input type="text" name="type_name" value="">
                     </td>
                 </tr>

                 <tr>
                     <td>排序</td>
                     <td>
                         <input type="text" name="sort" value="">
                     </td>
                 </tr>

                 <tr>
                     <td>是否显示</td>
                     <td>
                         <input type="radio" name="isshow" value="0">显示
                         <input type="radio" name="isshow" value="1">不显示
                     </td>
                 </tr>

                 <tr>
                     <td></td>
                     <td>
                         <input type="submit" value="添加分类">
                     </td>
                 </tr>
             </table>
         </form>

     </center>
</body>
</html>